#!/usr/bin/env node
// =============================================================================
// permission-contract — TS codegen.
//
// Reads permissions.json and emits src/role-permissions.ts for the
// @wazobiatech/helios-permissions SDK. Output preserves the closed
// `Permission` union that v0.1.0 / v0.2.0 hardcoded — typos in callers
// still surface at tsc time.
//
// Usage:
//   node scripts/codegen-ts.mjs <contract.json> > src/role-permissions.ts
//
// The generated file starts with a DO-NOT-EDIT header. The only input
// that changes the output is permissions.json.
// =============================================================================

import { readFileSync } from 'node:fs';

const [, , contractPath] = process.argv;
if (!contractPath) {
  console.error('usage: codegen-ts.mjs <contract.json>');
  process.exit(2);
}

const contract = JSON.parse(readFileSync(contractPath, 'utf8'));
const VERSION = contract.version;
const GENERATED_AT = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

function arrayLiteral(items, indent = 2) {
  if (items.length === 0) return '[]';
  const pad = ' '.repeat(indent);
  return '[\n' + items.map(p => `${pad}'${p}',`).join('\n') + `\n${' '.repeat(indent - 2)}]`;
}

function constantTuple(name, items) {
  return `const ${name} = ${arrayLiteral(items)} as const;`;
}

// -----------------------------------------------------------------------------
// Emit file
// -----------------------------------------------------------------------------

const lines = [];
const w = (s = '') => lines.push(s);

w(`// =============================================================================`);
w(`// AUTO-GENERATED — DO NOT EDIT.`);
w(`//`);
w(`// Source: permission-contract v${VERSION}`);
w(`// Generated at: ${GENERATED_AT}`);
w(`// Regenerate via: node scripts/codegen-ts.mjs permissions.json > src/role-permissions.ts`);
w(`//`);
w(`// The Permission union and ROLE_PERMISSIONS map are derived from the`);
w(`// language-agnostic JSON contract. To change the platform's role → permission`);
w(`// matrix, edit permissions.json in wazobiatech/permission-contract and`);
w(`// re-run codegen — do not edit this file by hand.`);
w(`//`);
w(`// Permission naming convention: \`{service}:{resource}:{action}\`.`);
w(`//   service  — one of: ${contract.services.join(', ')}`);
w(`//   resource — domain noun (project, users, posts, members, ...)`);
w(`//   action   — verb (view, write, delete, manage, ...)`);
w(`// =============================================================================`);
w();
w(`// -----------------------------------------------------------------------------`);
w(`// Permission vocabulary (one tuple per service)`);
w(`// -----------------------------------------------------------------------------`);
w();
for (const [service, perms] of Object.entries(contract.permissions)) {
  w(constantTuple(`${service.toUpperCase()}_PERMISSIONS`, perms));
}
w();
w(`/**`);
w(` * The full set of valid permission strings in the system.`);
w(` *`);
w(` * The union type is the precise closed set. The \`Permission\` exported`);
w(` * type is used everywhere callers need to gate a decision. Typos get`);
w(` * caught at compile time when assigned into ROLE_PERMISSIONS.`);
w(` */`);
w(`export type Permission =`);
for (const service of contract.services) {
  const tupleName = `${service.toUpperCase()}_PERMISSIONS`;
  w(`  | (typeof ${tupleName})[number]`);
}
w(`;`);
w();
w(`/**`);
w(` * The closed set of roles. Mirrors \`RoleType\` in Helios's Prisma schema.`);
w(` */`);
w(`export const ROLES = ${arrayLiteral(contract.roles)} as const;`);
w(`export type Role = (typeof ROLES)[number];`);
w();
w(`/**`);
w(` * Static role → permission map.`);
w(` *`);
w(` * Every role lists its permissions explicitly — there is no inheritance.`);
w(` * The contract validator (scripts/validate.mjs) enforces:`);
w(` *   - \`helios:tenant:switch\` is present in every role (universal perm).`);
w(` *   - \`helios:tenant:transfer\` is present only in OWNER (ZIN-4714).`);
w(` *   - Every role has >=1 permission.`);
w(` *   - No role references a perm outside the vocabulary.`);
w(` */`);
w(`export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {`);
for (const role of contract.roles) {
  const def = contract.role_permissions[role];
  w(`  ${role}: [`);
  for (const perm of def.permissions) {
    w(`    '${perm}',`);
  }
  w(`  ],`);
}
w(`} as const;`);
w();
w(`/**`);
w(` * Returns the read-only permission array for a role.`);
w(` *`);
w(` * The array is \`readonly\` so callers cannot accidentally mutate the`);
w(` * shared map. Spread it (\`[...resolvePermissions(role)]\`) if you need`);
w(` * a mutable copy.`);
w(` */`);
w(`export function resolvePermissions(role: Role): readonly Permission[] {`);
w(`  return ROLE_PERMISSIONS[role];`);
w(`}`);
w();
w(`/**`);
w(` * \`true\` if \`role\` is granted \`perm\`. Used by Helios's`);
w(` * PermissionResolverService when resolving per-tenant membership rows.`);
w(` */`);
w(`export function roleHasPermission(role: Role, perm: Permission): boolean {`);
w(`  return ROLE_PERMISSIONS[role].includes(perm);`);
w(`}`);
w();
w(`/**`);
w(` * Type guard: returns \`true\` if \`value\` is a known Permission string.`);
w(` */`);
w(`export function isPermission(value: unknown): value is Permission {`);
w(`  if (typeof value !== 'string') return false;`);
w(`  return (`);
const serviceChecks = contract.services.map(
  s => `    (${s.toUpperCase()}_PERMISSIONS as readonly string[]).includes(value)`,
);
w(serviceChecks.join(' ||\n'));
w(`  );`);
w(`}`);
w();
w(`/**`);
w(` * Type guard: returns \`true\` if \`value\` is a known Role string.`);
w(` */`);
w(`export function isRole(value: unknown): value is Role {`);
w(`  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);`);
w(`}`);

console.log(lines.join('\n') + '\n');