#!/usr/bin/env node
// =============================================================================
// permission-contract — Go codegen.
//
// Reads permissions.json and emits role_permissions.go for the
// wazobiatech/helios-permissions-go SDK. Output preserves the closed
// `Permission` type alias that callers depend on for compile-time typo
// detection.
//
// v1.3.0 codegen: perms are partitioned by `scope` into four tuples
// (SELF_PERMISSIONS, PLATFORM_PERMISSIONS, PROJECT_PERMISSIONS,
// DUAL_PERMISSIONS). The `PERM_SCOPE` map gives O(1) scope lookup at
// runtime — used by Helios's two-track resolver to gate which path
// (platform-user vs tenant-user) is valid for a given perm.
//
// Usage:
//   node scripts/codegen-go.mjs <contract.json> > role_permissions.go
//
// The generated file starts with a DO-NOT-EDIT header. The only input
// that changes the output is permissions.json.
//
// Output is deterministic: perms are sorted alphabetically inside each
// role for diff stability across contract versions.
// =============================================================================

import { readFileSync } from 'node:fs';

const [, , contractPath] = process.argv;
if (!contractPath) {
  console.error('usage: codegen-go.mjs <contract.json>');
  process.exit(2);
}

const contract = JSON.parse(readFileSync(contractPath, 'utf8'));
const VERSION = contract.version;
const GENERATED_AT = new Date().toISOString().slice(0, 10);

// Perms are objects in v1.3.0+. Flatten and bucket by scope.
const SELF = [];
const PLATFORM = [];
const PROJECT = [];
const DUAL = [];
const ALL_BY_NAME = []; // sorted list of { name, constName } for the const block
for (const [, perms] of Object.entries(contract.permissions)) {
  for (const p of perms) {
    const parts = p.name.split(':');
    const camel = parts.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
    const entry = { perm: p.name, constName: `Permission${camel}` };
    ALL_BY_NAME.push(entry);
    if (p.scope === 'self') SELF.push(entry);
    else if (p.scope === 'platform') PLATFORM.push(entry);
    else if (p.scope === 'project') PROJECT.push(entry);
    else if (p.scope === 'platform/project') DUAL.push(entry);
  }
}
ALL_BY_NAME.sort((a, b) => a.perm.localeCompare(b.perm));

// Sort perms alphabetically inside each role for diff stability.
const roles = contract.roles.map((role) => {
  const def = contract.role_permissions[role];
  return {
    role,
    perms: [...def.permissions].sort(),
  };
});

const lines = [];
const w = (s = '') => lines.push(s);

w(`// Code generated by permission-contract/codegen-go.mjs DO NOT EDIT.`);
w(`// Source: permission-contract v${VERSION}`);
w(`// Generated at: ${GENERATED_AT}`);
w(`// Regenerate via: node scripts/codegen-go.mjs permissions.json > role_permissions.go`);
w(`//`);
w(`// The Permission type, PERM_SCOPE map, and ROLE_PERMISSIONS map are derived`);
w(`// from the language-agnostic JSON contract. To change the platform's role →`);
w(`// permission matrix, edit permissions.json in wazobiatech/permission-contract`);
w(`// and re-run codegen — do not edit this file by hand.`);
w(`//`);
w(`// Permission naming convention: {service}:{resource}:{action}.`);
w(`//   service  — one of: ${contract.services.join(', ')}`);
w(`//   resource — domain noun (project, users, posts, members, ...)`);
w(`//   action   — verb (view, write, delete, manage, ...)`);
w(`//`);
w(`// v1.3.0 perm scopes — the resolver uses PERM_SCOPE[perm] to gate which`);
w(`// path (platform-user vs tenant-user) is valid for a given perm:`);
w(`//   self              — universal, granted implicitly (no role needed)`);
w(`//   platform          — granted via ROLE_PERMISSIONS (platform-user path);`);
w(`//                       cannot be bundled into a TenantRole`);
w(`//   project           — granted via TenantRole (tenant-user path);`);
w(`//                       cannot appear in ROLE_PERMISSIONS`);
w(`//   platform/project  — valid via either path (dual-scope).`);
w(`//`);
w(`// Package helios_permissions mirrors the TS / Python SDKs. Callers gate`);
w(`// decisions on the returned []Permission; a perm not listed in this file is`);
w(`// a typo and will fail to compile against the Permission type alias.`);
w(`package helios_permissions`);
w();
w(`// Role is the closed enum of platform roles. Mirrors the RoleType Prisma`);
w(`// enum in Helios. New roles must be added to the contract's roles[] array`);
w(`// and the codegen re-run.`);
w(`type Role string`);
w();
w(`const (`);
for (const r of contract.roles) {
  w(`\tRole${r.charAt(0) + r.slice(1).toLowerCase()} Role = "${r}"`);
}
w(`)`);
w();
w(`// Permission is the closed string union of every permission in the platform.`);
w(`// Compile-time guard: a perm not listed here is a typo.`);
w(`type Permission string`);
w();
w(`const (`);
for (const { perm, constName } of ALL_BY_NAME) {
  w(`\t${constName} Permission = "${perm}"`);
}
w(`)`);
w();
w(`// PermScope is the closed set of valid permission scopes. Mirrors the`);
w(`// contract's scope enum.`);
w(`type PermScope string`);
w();
w(`const (`);
w(`\tScopeSelf              PermScope = "self"`);
w(`\tScopePlatform          PermScope = "platform"`);
w(`\tScopeProject           PermScope = "project"`);
w(`\tScopePlatformProject   PermScope = "platform/project"`);
w(`)`);
w();
w(`// SELF_PERMISSIONS — universal perms granted implicitly to every`);
w(`// authenticated user. Never appear in any ROLE_PERMISSIONS entry.`);
w(`var SELF_PERMISSIONS = []Permission{`);
for (const { constName } of SELF) w(`\t${constName},`);
w(`}`);
w();
w(`// PLATFORM_PERMISSIONS — granted via ROLE_PERMISSIONS[role] (platform-user`);
w(`// path). Cannot be bundled into a TenantRole.`);
w(`var PLATFORM_PERMISSIONS = []Permission{`);
for (const { constName } of PLATFORM) w(`\t${constName},`);
w(`}`);
w();
w(`// PROJECT_PERMISSIONS — granted via TenantRole (tenant-user path). Cannot`);
w(`// appear in any ROLE_PERMISSIONS entry.`);
w(`var PROJECT_PERMISSIONS = []Permission{`);
for (const { constName } of PROJECT) w(`\t${constName},`);
w(`}`);
w();
w(`// DUAL_PERMISSIONS — valid via either the platform-user path`);
w(`// (ROLE_PERMISSIONS) or the tenant-user path (TenantRole bundle).`);
w(`var DUAL_PERMISSIONS = []Permission{`);
for (const { constName } of DUAL) w(`\t${constName},`);
w(`}`);
w();
w(`// PERM_SCOPE — perm → scope lookup, populated at module load. The two-track`);
w(`// resolver in Helios checks PERM_SCOPE[perm] to decide which path`);
w(`// (platform-user vs tenant-user) is valid for the perm.`);
w(`var PERM_SCOPE = map[Permission]PermScope{`);
for (const { perm, constName } of SELF) w(`\t${constName}: ScopeSelf,`);
for (const { perm, constName } of PLATFORM) w(`\t${constName}: ScopePlatform,`);
for (const { perm, constName } of PROJECT) w(`\t${constName}: ScopeProject,`);
for (const { perm, constName } of DUAL) w(`\t${constName}: ScopePlatformProject,`);
w(`}`);
w();
w(`// Roles lists every role in the platform. Same order as the contract's`);
w(`// roles[] array.`);
w(`var Roles = []Role{`);
for (const r of contract.roles) {
  w(`\tRole${r.charAt(0) + r.slice(1).toLowerCase()},`);
}
w(`}`);
w();
w(`// IsValidPermission reports whether p is a known permission string.`);
w(`func IsValidPermission(p Permission) bool {`);
w(`\t_, ok := PERM_SCOPE[p]`);
w(`\treturn ok`);
w(`}`);
w();
w(`// IsValidRole reports whether r is a known role string.`);
w(`func IsValidRole(r Role) bool {`);
w(`\tswitch r {`);
for (const r of contract.roles) {
  w(`\tcase Role${r.charAt(0) + r.slice(1).toLowerCase()}:`);
  w(`\t\treturn true`);
}
w(`\t}`);
w(`\treturn false`);
w(`}`);
w();
w(`// IsSelfScope reports whether perm has scope "self" (universal — granted`);
w(`// without any role lookup). Used by the resolver's Step 1.`);
w(`func IsSelfScope(perm Permission) bool {`);
w(`\treturn PERM_SCOPE[perm] == ScopeSelf`);
w(`}`);
w();
w(`// IsPlatformGrantable reports whether perm is grantable via the`);
w(`// platform-user path (scope is "platform" or "platform/project").`);
w(`func IsPlatformGrantable(perm Permission) bool {`);
w(`\ts := PERM_SCOPE[perm]`);
w(`\treturn s == ScopePlatform || s == ScopePlatformProject`);
w(`}`);
w();
w(`// IsTenantGrantable reports whether perm is grantable via the tenant-user`);
w(`// path. Scope "project" and "platform/project" are grantable; any perm NOT`);
w(`// in PERM_SCOPE is treated as tenant-defined and therefore grantable via`);
w(`// TenantRole.`);
w(`func IsTenantGrantable(perm string) bool {`);
w(`\ts, ok := PERM_SCOPE[Permission(perm)]`);
w(`\tif !ok {`);
w(`\t\treturn true`);
w(`\t}`);
w(`\treturn s == ScopeProject || s == ScopePlatformProject`);
w(`}`);
w();
w(`// ROLE_PERMISSIONS is the canonical role → permission map. Every role lists`);
w(`// its permissions explicitly — there is no inheritance. The contract`);
w(`// validator (scripts/validate.mjs) enforces:`);
w(`//   - helios:tenant:switch:self is present as a self-scope perm (universal).`);
w(`//   - helios:tenant:transfer is OWNER-only (platform scope).`);
w(`//   - Every role has >= 1 permission.`);
w(`//   - No role references a perm outside the vocabulary.`);
w(`//   - No self or project perms in any role.`);
w(`var ROLE_PERMISSIONS = map[Role][]Permission{`);
for (const { role, perms } of roles) {
  const roleConst = `Role${role.charAt(0) + role.slice(1).toLowerCase()}`;
  w(`\t${roleConst}: {`);
  for (const p of perms) {
    const parts = p.split(':');
    const camel = parts.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
    w(`\t\tPermission${camel},`);
  }
  w(`\t},`);
}
w(`}`);
w();
w(`// ResolvePermissions returns ROLE_PERMISSIONS[role]. Returns an empty slice`);
w(`// for unknown roles (defensive — caller code should be using the typed`);
w(`// Role constants, but a runtime string from an untrusted source might not be).`);
w(`func ResolvePermissions(role Role) []Permission {`);
w(`\tif perms, ok := ROLE_PERMISSIONS[role]; ok {`);
w(`\t\treturn perms`);
w(`\t}`);
w(`\treturn []Permission{}`);
w(`}`);
w();
w(`// RoleHasPermission reports whether role is granted perm. Both args must be`);
w(`// typed constants for the call to compile — a typo in a perm string will`);
w(`// not satisfy the Permission type alias.`);
w(`func RoleHasPermission(role Role, perm Permission) bool {`);
w(`\tfor _, p := range ROLE_PERMISSIONS[role] {`);
w(`\t\tif p == perm {`);
w(`\t\treturn true`);
w(`\t\t}`);
w(`\t}`);
w(`\treturn false`);
w(`}`);

console.log(lines.join('\n') + '\n');