#!/usr/bin/env node
// =============================================================================
// permission-contract — TS codegen.
//
// Reads permissions.json and emits src/role-permissions.ts for the
// @wazobiatech/helios-permissions SDK. Output preserves the closed
// `Permission` union that v0.1.0 / v0.2.0 / v0.3.0 hardcoded — typos in
// callers still surface at tsc time.
//
// v1.3.0 codegen: perms are partitioned by `scope` into four tuples
// (SELF_PERMISSIONS, PLATFORM_PERMISSIONS, PROJECT_PERMISSIONS,
// DUAL_PERMISSIONS). The `PERM_SCOPE` map gives O(1) scope lookup at
// runtime — used by Helios's two-track resolver to gate which path
// (platform-user vs tenant-user) is valid for a given perm.
//
// Usage:
//   node scripts/codegen-ts.mjs <contract.json> > src/role-permissions.ts
//
// The generated file starts with a DO-NOT-EDIT header. The only input
// that changes the output is permissions.json.
// =============================================================================

import { readFileSync } from 'node:fs';

const [, , contractPath] = process.argv;
if (!contractPath) {
  console.error('usage: codegen-ts.mjs <contract.json>');
  process.exit(2);
}

const contract = JSON.parse(readFileSync(contractPath, 'utf8'));
const VERSION = contract.version;
const GENERATED_AT = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

// Perms are objects in v1.3.0+. Flatten and bucket by scope.
const allPerms = [];
const SELF = [];
const PLATFORM = [];
const PROJECT = [];
const DUAL = [];
for (const [service, perms] of Object.entries(contract.permissions)) {
  for (const p of perms) {
    allPerms.push(p);
    if (p.scope === 'self') SELF.push(p.name);
    else if (p.scope === 'platform') PLATFORM.push(p.name);
    else if (p.scope === 'project') PROJECT.push(p.name);
    else if (p.scope === 'platform/project') DUAL.push(p.name);
  }
}

function arrayLiteral(items, indent = 2) {
  if (items.length === 0) return '[]';
  const pad = ' '.repeat(indent);
  return '[\n' + items.map(p => `${pad}'${p}',`).join('\n') + `\n${' '.repeat(indent - 2)}]`;
}

function constantTuple(name, items) {
  return `export const ${name} = ${arrayLiteral(items)} as const;`;
}

// -----------------------------------------------------------------------------
// Emit file
// -----------------------------------------------------------------------------

const lines = [];
const w = (s = '') => lines.push(s);

w(`// =============================================================================`);
w(`// AUTO-GENERATED — DO NOT EDIT.`);
w(`//`);
w(`// Source: permission-contract v${VERSION}`);
w(`// Generated at: ${GENERATED_AT}`);
w(`// Regenerate via: node scripts/codegen-ts.mjs permissions.json > src/role-permissions.ts`);
w(`//`);
w(`// The Permission union, PERM_SCOPE map, and ROLE_PERMISSIONS map are derived`);
w(`// from the language-agnostic JSON contract. To change the platform's role →`);
w(`// permission matrix, edit permissions.json in wazobiatech/permission-contract`);
w(`// and re-run codegen — do not edit this file by hand.`);
w(`//`);
w(`// Permission naming convention: \`{service}:{resource}:{action}\`.`);
w(`//   service  — one of: ${contract.services.join(', ')}`);
w(`//   resource — domain noun (project, users, posts, members, ...)`);
w(`//   action   — verb (view, write, delete, manage, ...)`);
w(`//`);
w(`// v1.3.0 perm scopes — the resolver uses \`PERM_SCOPE[perm]\` to gate which`);
w(`// path (platform-user vs tenant-user) is valid for a given perm:`);
w(`//   self              — universal, granted implicitly (no role needed)`);
w(`//   platform          — granted via ROLE_PERMISSIONS (platform-user path);`);
w(`//                       cannot be bundled into a TenantRole`);
w(`//   project           — granted via TenantRole (tenant-user path);`);
w(`//                       cannot appear in ROLE_PERMISSIONS`);
w(`//   platform/project  — valid via either path (dual-scope).`);
w(`// =============================================================================`);
w();
w(`// -----------------------------------------------------------------------------`);
w(`// Permission vocabulary, partitioned by scope (v1.3.0+)`);
w(`// -----------------------------------------------------------------------------`);
w();
w(`/**`);
w(` * Self-scope perms — universal, granted implicitly to every authenticated`);
w(` * user. Never appear in any ROLE_PERMISSIONS entry.`);
w(` */`);
w(constantTuple('SELF_PERMISSIONS', SELF));
w();
w(`/**`);
w(` * Platform-scope perms — granted via ROLE_PERMISSIONS[role] (platform-user`);
w(` * path). Cannot be bundled into a TenantRole.`);
w(` */`);
w(constantTuple('PLATFORM_PERMISSIONS', PLATFORM));
w();
w(`/**`);
w(` * Project-scope perms — granted via TenantRole (tenant-user path). Cannot`);
w(` * appear in any ROLE_PERMISSIONS entry.`);
w(` */`);
w(constantTuple('PROJECT_PERMISSIONS', PROJECT));
w();
w(`/**`);
w(` * Dual-scope perms — valid via either the platform-user path`);
w(` * (ROLE_PERMISSIONS) or the tenant-user path (TenantRole bundle).`);
w(` */`);
w(constantTuple('DUAL_PERMISSIONS', DUAL));
w();
w(`/**`);
w(` * The closed set of valid permission strings in the system.`);
w(` *`);
w(` * The union type is the precise closed set. The \`Permission\` exported`);
w(` * type is used everywhere callers need to gate a decision. Typos get`);
w(` * caught at compile time when assigned into ROLE_PERMISSIONS.`);
w(` */`);
w(`export type SelfPermission = (typeof SELF_PERMISSIONS)[number];`);
w(`export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[number];`);
w(`export type ProjectPermission = (typeof PROJECT_PERMISSIONS)[number];`);
w(`export type DualPermission = (typeof DUAL_PERMISSIONS)[number];`);
w(`export type Permission =`);
w(`  | SelfPermission`);
w(`  | PlatformPermission`);
w(`  | ProjectPermission`);
w(`  | DualPermission;`);
w();
w(`/**`);
w(` * Perm → scope lookup, populated at module load. The two-track resolver in`);
w(` * Helios checks \`PERM_SCOPE[perm]\` to decide which path (platform-user vs`);
w(` * tenant-user) is valid for the perm.`);
w(` */`);
w(`export const PERM_SCOPE: Record<Permission, PermScope> = {`);
w(`  // self`);
for (const p of SELF) w(`  '${p}': 'self',`);
w(`  // platform`);
for (const p of PLATFORM) w(`  '${p}': 'platform',`);
w(`  // project`);
for (const p of PROJECT) w(`  '${p}': 'project',`);
w(`  // platform/project`);
for (const p of DUAL) w(`  '${p}': 'platform/project',`);
w(`};`);
w();
w(`/** The four valid perm scopes. Mirrors the contract's \`scope\` enum. */`);
w(`export type PermScope = 'self' | 'platform' | 'project' | 'platform/project';`);
w();
w(`/**`);
w(` * The closed set of roles. Mirrors \`RoleType\` in Helios's Prisma schema.`);
w(` *`);
w(` * ROLE_PERMISSIONS only contains \`platform\` and \`platform/project\``);
w(` * perms; \`self\` perms are universal (granted by the resolver's Step 1),`);
w(` * and \`project\` perms are for tenant users via TenantRole.`);
w(` */`);
w(`export const ROLES = ${arrayLiteral(contract.roles)} as const;`);
w(`export type Role = (typeof ROLES)[number];`);
w();
w(`/**`);
w(` * Static role → permission map.`);
w(` *`);
w(` * Every role lists its permissions explicitly — there is no inheritance.`);
w(` * The contract validator (scripts/validate.mjs) enforces:`);
w(` *   - \`helios:tenant:switch:self\` is present as a self-scope perm (universal).`);
w(` *   - \`helios:tenant:transfer\` is OWNER-only (platform scope).`);
w(` *   - Every role has >=1 permission.`);
w(` *   - No role references a perm outside the vocabulary.`);
w(` *   - No self or project perms in any role.`);
w(` */`);
w(`export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {`);
for (const role of contract.roles) {
  const def = contract.role_permissions[role];
  w(`  ${role}: [`);
  for (const perm of def.permissions) {
    w(`    '${perm}',`);
  }
  w(`  ],`);
}
w(`} as const;`);
w();
w(`/**`);
w(` * Returns the read-only permission array for a role.`);
w(` *`);
w(` * The array is \`readonly\` so callers cannot accidentally mutate the`);
w(` * shared map. Spread it (\`[...resolvePermissions(role)]\`) if you need`);
w(` * a mutable copy.`);
w(` */`);
w(`export function resolvePermissions(role: Role): readonly Permission[] {`);
w(`  return ROLE_PERMISSIONS[role];`);
w(`}`);
w();
w(`/**`);
w(` * \`true\` if \`role\` is granted \`perm\`. Used by Helios's`);
w(` * PermissionResolverService for the platform-user path (Step 2 of`);
w(` * the two-track resolver).`);
w(` */`);
w(`export function roleHasPermission(role: Role, perm: Permission): boolean {`);
w(`  return ROLE_PERMISSIONS[role].includes(perm);`);
w(`}`);
w();
w(`/**`);
w(` * \`true\` if \`perm\` has scope \`self\` (universal — granted without`);
w(` * any role lookup). Used by the resolver's Step 1.`);
w(` */`);
w(`export function isSelfScope(perm: Permission): boolean {`);
w(`  return PERM_SCOPE[perm] === 'self';`);
w(`}`);
w();
w(`/**`);
w(` * \`true\` if \`perm\` is grantable via the platform-user path (scope`);
w(` * is \`platform\` or \`platform/project\`).`);
w(` */`);
w(`export function isPlatformGrantable(perm: Permission): boolean {`);
w(`  const s = PERM_SCOPE[perm];`);
w(`  return s === 'platform' || s === 'platform/project';`);
w(`}`);
w();
w(`/**`);
w(` * \`true\` if \`perm\` is grantable via the tenant-user path (scope is`);
w(` * \`project\` or \`platform/project\`, OR scope is unknown — tenant-defined`);
w(` * perms are always grantable via TenantRole).`);
w(` */`);
w(`export function isTenantGrantable(perm: Permission | string): boolean {`);
w(`  if (!(perm in PERM_SCOPE)) return true; // tenant-defined perm`);
w(`  const s = PERM_SCOPE[perm as Permission];`);
w(`  return s === 'project' || s === 'platform/project';`);
w(`}`);
w();
w(`/**`);
w(` * Type guard: returns \`true\` if \`value\` is a known Permission string.`);
w(` */`);
w(`export function isPermission(value: unknown): value is Permission {`);
w(`  if (typeof value !== 'string') return false;`);
w(`  return value in PERM_SCOPE;`);
w(`}`);
w();
w(`/**`);
w(` * Type guard: returns \`true\` if \`value\` is a known Role string.`);
w(` */`);
w(`export function isRole(value: unknown): value is Role {`);
w(`  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);`);
w(`}`);

console.log(lines.join('\n') + '\n');