#!/usr/bin/env node
// =============================================================================
// permission-contract — Go codegen.
//
// Reads permissions.json and emits role_permissions.go for the
// wazobiatech/helios-permissions-go SDK. Output preserves the closed
// `Permission` type alias that callers depend on for compile-time typo
// detection.
//
// Usage:
//   node scripts/codegen-go.mjs <contract.json> > role_permissions.go
//
// The generated file starts with a DO-NOT-EDIT header. The only input
// that changes the output is permissions.json.
//
// Output is deterministic: perms are sorted alphabetically inside each
// role for diff stability across contract versions.
// =============================================================================

import { readFileSync } from 'node:fs';

const [, , contractPath] = process.argv;
if (!contractPath) {
  console.error('usage: codegen-go.mjs <contract.json>');
  process.exit(2);
}

const contract = JSON.parse(readFileSync(contractPath, 'utf8'));
const VERSION = contract.version;
const GENERATED_AT = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

// Sort perms alphabetically inside each role for diff stability.
const roles = contract.roles.map((role) => {
  const def = contract.role_permissions[role];
  return {
    role,
    perms: [...def.permissions].sort(),
  };
});

const allPerms = Object.values(contract.permissions).flat();
const permConsts = allPerms
  .slice()
  .sort()
  .map((p) => {
    // Build the const name from the perm string. "athens:project:view"
    // → "PermissionAthensProjectView". Preserves uniqueness across
    // services (the contract validator enforces no overlap).
    const parts = p.split(':');
    const camel = parts
      .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
      .join('');
    return {
      perm: p,
      constName: `Permission${camel}`,
    };
  });

const lines = [];
const w = (s = '') => lines.push(s);

w(`// Code generated by permission-contract/codegen-go.mjs DO NOT EDIT.`);
w(`// Source: permission-contract v${VERSION}`);
w(`// Generated at: ${GENERATED_AT}`);
w(`// Regenerate via: node scripts/codegen-go.mjs permissions.json > role_permissions.go`);
w(`//`);
w(`// The Permission type and ROLE_PERMISSIONS map are derived from the`);
w(`// language-agnostic JSON contract. To change the platform's role → permission`);
w(`// matrix, edit permissions.json in wazobiatech/permission-contract and re-run`);
w(`// codegen — do not edit this file by hand.`);
w(`//`);
w(`// Permission naming convention: {service}:{resource}:{action}.`);
w(`//   service  — one of: ${contract.services.join(', ')}`);
w(`//   resource — domain noun (project, users, posts, members, ...)`);
w(`//   action   — verb (view, write, delete, manage, ...)`);
w(`//`);
w(`// Package helios_permissions mirrors the TS / Python SDKs. Callers gate`);
w(`// decisions on the returned []Permission; a perm not listed in this file is`);
w(`// a typo and will fail to compile against the Permission type alias.`);
w(`package helios_permissions`);
w();
w(`// Role is the closed enum of platform roles. Mirrors the RoleType Prisma`);
w(`// enum in Helios. New roles must be added to the contract's roles[] array`);
w(`// and the codegen re-run.`);
w(`type Role string`);
w();
w(`const (`);
for (const r of contract.roles) {
  w(`\tRole${r.charAt(0) + r.slice(1).toLowerCase()} Role = "${r}"`);
}
w(`)`);
w();
w(`// Permission is the closed string union of every permission in the platform.`);
w(`// Compile-time guard: a perm not listed here is a typo.`);
w(`type Permission string`);
w();
w(`const (`);
for (const { perm, constName } of permConsts) {
  w(`\t${constName} Permission = "${perm}"`);
}
w(`)`);
w();
w(`// Roles lists every role in the platform. Same order as the contract's`);
w(`// roles[] array.`);
w(`var Roles = []Role{`);
for (const r of contract.roles) {
  w(`\tRole${r.charAt(0) + r.slice(1).toLowerCase()},`);
}
w(`}`);
w();
w(`// IsValidPermission reports whether p is a known permission string.`);
w(`func IsValidPermission(p Permission) bool {`);
w(`\tswitch p {`);
for (const { perm, constName } of permConsts) {
  w(`\tcase ${constName}:`);
  w(`\t\treturn true`);
}
w(`\t}`);
w(`\treturn false`);
w(`}`);
w();
w(`// IsValidRole reports whether r is a known role string.`);
w(`func IsValidRole(r Role) bool {`);
w(`\tswitch r {`);
for (const r of contract.roles) {
  w(`\tcase Role${r.charAt(0) + r.slice(1).toLowerCase()}:`);
  w(`\t\treturn true`);
}
w(`\t}`);
w(`\treturn false`);
w(`}`);
w();
w(`// ROLE_PERMISSIONS is the canonical role → permission map. Every role lists`);
w(`// its permissions explicitly — there is no inheritance. The contract`);
w(`// validator (scripts/validate.mjs) enforces:`);
w(`//   - helios:tenant:switch is present in every role (universal perm).`);
w(`//   - helios:tenant:transfer is present only in OWNER (ZIN-4714).`);
w(`//   - Every role has >= 1 permission.`);
w(`//   - No role references a perm outside the vocabulary.`);
w(`var ROLE_PERMISSIONS = map[Role][]Permission{`);
for (const { role, perms } of roles) {
  const roleConst = `Role${role.charAt(0) + role.slice(1).toLowerCase()}`;
  w(`\t${roleConst}: {`);
  for (const p of perms) {
    const parts = p.split(':');
    const camel = parts
      .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
      .join('');
    w(`\t\tPermission${camel},`);
  }
  w(`\t},`);
}
w(`}`);
w();
w(`// ResolvePermissions returns ROLE_PERMISSIONS[role]. Returns an empty slice`);
w(`// for unknown roles (defensive — caller code should be using the typed`);
w(`// Role constants, but a runtime string from an untrusted source might not be).`);
w(`func ResolvePermissions(role Role) []Permission {`);
w(`\tif perms, ok := ROLE_PERMISSIONS[role]; ok {`);
w(`\t\treturn perms`);
w(`\t}`);
w(`\treturn []Permission{}`);
w(`}`);
w();
w(`// RoleHasPermission reports whether role is granted perm. Both args must be`);
w(`// typed constants for the call to compile — a typo in a perm string will`);
w(`// not satisfy the Permission type alias.`);
w(`func RoleHasPermission(role Role, perm Permission) bool {`);
w(`\tfor _, p := range ROLE_PERMISSIONS[role] {`);
w(`\t\tif p == perm {`);
w(`\t\t\treturn true`);
w(`\t\t}`);
w(`\t}`);
w(`\treturn false`);
w(`}`);

console.log(lines.join('\n') + '\n');
