#!/usr/bin/env node
// =============================================================================
// permission-contract — PHP codegen.
//
// Reads permissions.json and emits three files for the
// wazobia/helios-permissions Laravel SDK:
//
//   Role.php             — closed Role enum
//   Permission.php       — closed Permission enum
//   RolePermissions.php  — role → perm map + helpers
//
// Output preserves the closed Permission enum (PHP 8.1 backed string)
// for compile-time typo detection.
//
// Usage:
//   node scripts/codegen-php.mjs <contract.json> <out-dir>
//
// The generated files start with a DO-NOT-EDIT header. The only input
// that changes the output is permissions.json.
//
// Output is deterministic: perms are sorted alphabetically inside each
// role for diff stability across contract versions.
// =============================================================================

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve as pathResolve } from 'node:path';

const [, , contractPath, outDir] = process.argv;
if (!contractPath || !outDir) {
  console.error('usage: codegen-php.mjs <contract.json> <out-dir>');
  process.exit(2);
}

const contract = JSON.parse(readFileSync(contractPath, 'utf8'));
const VERSION = contract.version;
const GENERATED_AT = new Date().toISOString().slice(0, 10);

const roles = contract.roles.map((role) => {
  const def = contract.role_permissions[role];
  return {
    role,
    perms: [...def.permissions].sort(),
  };
});

const allPerms = Object.values(contract.permissions).flat();
const sortedPerms = [...allPerms].sort();

const caseName = (s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
const permCaseName = (p) => {
  const parts = p.split(':');
  return parts.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
};

const header = (extraComment) => `<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v${VERSION}
 * Generated at: ${GENERATED_AT}
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * ${extraComment}
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: ${contract.services.join(', ')}
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\\HeliosPermissions;
`;

// === Role.php ===
let roleLines = [];
roleLines.push(header('Role — closed enum of platform roles. Backed by the same string values\n * Helios\'s Prisma RoleType uses. New roles must be added to the contract\'s\n * roles[] array and the codegen re-run.'));
roleLines.push(`enum Role: string`);
roleLines.push(`{`);
for (const r of contract.roles) {
  roleLines.push(`    case ${caseName(r)} = '${r}';`);
}
roleLines.push(`}`);
roleLines.push(``);
const rolePhp = roleLines.join('\n');

// === Permission.php ===
let permLines = [];
permLines.push(header('Permission — closed enum of every permission string in the platform.\n * PHP 8.1 backed enums give compile-time typo protection: a perm not\n * listed here fails the type checker.'));
permLines.push(`enum Permission: string`);
permLines.push(`{`);
for (const p of sortedPerms) {
  permLines.push(`    case ${permCaseName(p)} = '${p}';`);
}
permLines.push(`}`);
permLines.push(``);
const permPhp = permLines.join('\n');

// === RolePermissions.php ===
let rpLines = [];
rpLines.push(header('RolePermissions — canonical role → permission map and helpers.\n *\n * Mirrors the TS / Python / Go SDKs. Every role lists its permissions\n * explicitly — no inheritance. The contract validator\n * (scripts/validate.mjs) enforces:\n *   - helios:tenant:switch is present in every role (universal perm).\n *   - helios:tenant:transfer is present only in OWNER (ZIN-4714).\n *   - Every role has >= 1 permission.\n *   - No role references a perm outside the vocabulary.'));
rpLines.push(`final class RolePermissions`);
rpLines.push(`{`);
rpLines.push(`    /** Every role in the platform. Same order as the contract's roles[]. */`);
rpLines.push(`    public const ROLES = [`);
for (const r of contract.roles) {
  rpLines.push(`        Role::${caseName(r)},`);
}
rpLines.push(`    ];`);
rpLines.push(``);
rpLines.push(`    /** @var array<string, list<Permission>> role → perm map. */`);
rpLines.push(`    private const ROLE_PERMISSIONS = [`);
for (const { role, perms } of roles) {
  rpLines.push(`        '${role}' => [`);
  for (const p of perms) {
    rpLines.push(`            Permission::${permCaseName(p)},`);
  }
  rpLines.push(`        ],`);
}
rpLines.push(`    ];`);
rpLines.push(``);
rpLines.push(`    /**`);
rpLines.push(`     * Return the permission array for a role. Empty for unknown roles.`);
rpLines.push(`     *`);
rpLines.push(`     * @return list<Permission>`);
rpLines.push(`     */`);
rpLines.push(`    public static function resolve(Role $role): array`);
rpLines.push(`    {`);
rpLines.push(`        return self::ROLE_PERMISSIONS[$role->value] ?? [];`);
rpLines.push(`    }`);
rpLines.push(``);
rpLines.push(`    /**`);
rpLines.push(`     * True if role is granted perm. Both args must be typed enums — a typo`);
rpLines.push(`     * in a perm string will not satisfy the Permission type.`);
rpLines.push(`     */`);
rpLines.push(`    public static function has(Role $role, Permission $perm): bool`);
rpLines.push(`    {`);
rpLines.push(`        foreach (self::resolve($role) as $p) {`);
rpLines.push(`            if ($p === $perm) {`);
rpLines.push(`                return true;`);
rpLines.push(`            }`);
rpLines.push(`        }`);
rpLines.push(`        return false;`);
rpLines.push(`    }`);
rpLines.push(``);
rpLines.push(`    /**`);
rpLines.push(`     * True if p is a known Permission value. Used for runtime validation of`);
rpLines.push(`     * strings arriving from an untrusted source (request bodies, DB rows, etc).`);
rpLines.push(`     */`);
rpLines.push(`    public static function isValidPermission(Permission $perm): bool`);
rpLines.push(`    {`);
rpLines.push(`        return in_array($perm, Permission::cases(), true);`);
rpLines.push(`    }`);
rpLines.push(`}`);
rpLines.push(``);
const rpPhp = rpLines.join('\n');

mkdirSync(pathResolve(outDir), { recursive: true });
writeFileSync(pathResolve(outDir, 'Role.php'), rolePhp);
writeFileSync(pathResolve(outDir, 'Permission.php'), permPhp);
writeFileSync(pathResolve(outDir, 'RolePermissions.php'), rpPhp);
console.log(`wrote ${pathResolve(outDir, 'Role.php')}`);
console.log(`wrote ${pathResolve(outDir, 'Permission.php')}`);
console.log(`wrote ${pathResolve(outDir, 'RolePermissions.php')}`);
