<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.5.0
 * Generated at: 2026-06-30
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * PermScope — closed enum of valid permission scopes. Mirrors the
 * contract's scope enum. v1.3.0+.
 *
 * Scope semantics:
 *   self              — universal, granted implicitly to every user
 *   platform          — granted via ROLE_PERMISSIONS (platform-user path)
 *   project           — granted via TenantRole (tenant-user path)
 *   platform/project  — valid via either path
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

enum PermScope: string
{
    case Self = 'self';
    case Platform = 'platform';
    case Project = 'project';
    case PlatformProject = 'platform/project';
}
