<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.3.0
 * Generated at: 2026-06-22
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * Permission — closed enum of every permission string in the platform.
 * PHP 8.1 backed enums give compile-time typo protection: a perm not
 * listed here fails the type checker.
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

enum Permission: string
{
    case AthensProjectDelete = 'athens:project:delete';
    case AthensProjectUpdate = 'athens:project:update';
    case AthensProjectView = 'athens:project:view';
    case AthensServicesDisable = 'athens:services:disable';
    case AthensServicesEnable = 'athens:services:enable';
    case AthensTeamInvite = 'athens:team:invite';
    case AthensTeamRemove = 'athens:team:remove';
    case HeliosInvitationsCreate = 'helios:invitations:create';
    case HeliosInvitationsRevoke = 'helios:invitations:revoke';
    case HeliosMembersInvite = 'helios:members:invite';
    case HeliosMembersRemove = 'helios:members:remove';
    case HeliosMembersView = 'helios:members:view';
    case HeliosRolesAssign = 'helios:roles:assign';
    case HeliosRolesRevoke = 'helios:roles:revoke';
    case HeliosTenantSwitchSelf = 'helios:tenant:switch:self';
    case HeliosTenantTransfer = 'helios:tenant:transfer';
    case MercuryApi_keysManage = 'mercury:api_keys:manage';
    case MercuryUserReadSelf = 'mercury:user:read:self';
    case MercuryUserWriteSelf = 'mercury:user:write:self';
    case MercuryUsersRead = 'mercury:users:read';
    case MercuryUsersWrite = 'mercury:users:write';
    case MuseAuthorCreate = 'muse:author:create';
    case MuseAuthorDelete = 'muse:author:delete';
    case MuseAuthorRead = 'muse:author:read';
    case MuseBlogCreate = 'muse:blog:create';
    case MuseBlogRead = 'muse:blog:read';
    case MuseDraftsRead = 'muse:drafts:read';
    case MuseDraftsWrite = 'muse:drafts:write';
    case MusePostsDelete = 'muse:posts:delete';
    case MusePostsRead = 'muse:posts:read';
    case MusePostsWrite = 'muse:posts:write';
}
