<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.0.0
 * Generated at: 2026-06-19
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * RolePermissions — canonical role → permission map and helpers.
 *
 * Mirrors the TS / Python / Go SDKs. Every role lists its permissions
 * explicitly — no inheritance. The contract validator
 * (scripts/validate.mjs) enforces:
 *   - helios:tenant:switch is present in every role (universal perm).
 *   - helios:tenant:transfer is present only in OWNER (ZIN-4714).
 *   - Every role has >= 1 permission.
 *   - No role references a perm outside the vocabulary.
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

final class RolePermissions
{
    /** Every role in the platform. Same order as the contract's roles[]. */
    public const ROLES = [
        Role::Owner,
        Role::Admin,
        Role::Editor,
        Role::Viewer,
    ];

    /** @var array<string, list<Permission>> role → perm map. */
    private const ROLE_PERMISSIONS = [
        'OWNER' => [
            Permission::AthensProjectDelete,
            Permission::AthensProjectUpdate,
            Permission::AthensProjectView,
            Permission::AthensServicesDisable,
            Permission::AthensServicesEnable,
            Permission::AthensTeamInvite,
            Permission::AthensTeamRemove,
            Permission::HeliosInvitationsCreate,
            Permission::HeliosInvitationsRevoke,
            Permission::HeliosMembersInvite,
            Permission::HeliosMembersRemove,
            Permission::HeliosMembersView,
            Permission::HeliosRolesAssign,
            Permission::HeliosRolesRevoke,
            Permission::HeliosTenantSwitch,
            Permission::HeliosTenantTransfer,
            Permission::MercuryApi_keysManage,
            Permission::MercuryConnectionsRead,
            Permission::MercuryUsersRead,
            Permission::MercuryUsersWrite,
            Permission::MuseDraftsRead,
            Permission::MuseDraftsWrite,
            Permission::MusePostsDelete,
            Permission::MusePostsRead,
            Permission::MusePostsWrite,
        ],
        'ADMIN' => [
            Permission::AthensProjectUpdate,
            Permission::AthensProjectView,
            Permission::AthensServicesDisable,
            Permission::AthensServicesEnable,
            Permission::AthensTeamInvite,
            Permission::HeliosInvitationsCreate,
            Permission::HeliosInvitationsRevoke,
            Permission::HeliosMembersInvite,
            Permission::HeliosMembersRemove,
            Permission::HeliosMembersView,
            Permission::HeliosRolesAssign,
            Permission::HeliosRolesRevoke,
            Permission::HeliosTenantSwitch,
            Permission::MercuryApi_keysManage,
            Permission::MercuryConnectionsRead,
            Permission::MercuryUsersRead,
            Permission::MercuryUsersWrite,
            Permission::MuseDraftsRead,
            Permission::MuseDraftsWrite,
            Permission::MusePostsRead,
            Permission::MusePostsWrite,
        ],
        'EDITOR' => [
            Permission::AthensProjectView,
            Permission::HeliosMembersView,
            Permission::HeliosTenantSwitch,
            Permission::MercuryConnectionsRead,
            Permission::MercuryUsersRead,
            Permission::MuseDraftsRead,
            Permission::MuseDraftsWrite,
            Permission::MusePostsRead,
            Permission::MusePostsWrite,
        ],
        'VIEWER' => [
            Permission::AthensProjectView,
            Permission::HeliosMembersView,
            Permission::HeliosTenantSwitch,
            Permission::MercuryConnectionsRead,
            Permission::MercuryUsersRead,
            Permission::MuseDraftsRead,
            Permission::MusePostsRead,
        ],
    ];

    /**
     * Return the permission array for a role. Empty for unknown roles.
     *
     * @return list<Permission>
     */
    public static function resolve(Role $role): array
    {
        return self::ROLE_PERMISSIONS[$role->value] ?? [];
    }

    /**
     * True if role is granted perm. Both args must be typed enums — a typo
     * in a perm string will not satisfy the Permission type.
     */
    public static function has(Role $role, Permission $perm): bool
    {
        foreach (self::resolve($role) as $p) {
            if ($p === $perm) {
                return true;
            }
        }
        return false;
    }

    /**
     * True if p is a known Permission value. Used for runtime validation of
     * strings arriving from an untrusted source (request bodies, DB rows, etc).
     */
    public static function isValidPermission(Permission $perm): bool
    {
        return in_array($perm, Permission::cases(), true);
    }
}
