<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.7.0
 * Generated at: 2026-07-20
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * Role — closed enum of platform roles. Backed by the same string values
 * Helios's Prisma RoleType uses. New roles must be added to the contract's
 * roles[] array and the codegen re-run.
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios, zeta
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

enum Role: string
{
    case Owner = 'OWNER';
    case Admin = 'ADMIN';
    case Editor = 'EDITOR';
    case Viewer = 'VIEWER';
}
