<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.3.0
 * Generated at: 2026-06-22
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * RolePermissions — canonical role → permission map, scope lookup, and helpers.
 *
 * Mirrors the TS / Python / Go SDKs. Every role lists its permissions
 * explicitly — no inheritance. The contract validator
 * (scripts/validate.mjs) enforces:
 *   - helios:tenant:switch:self is present as a self-scope perm (universal).
 *   - helios:tenant:transfer is OWNER-only (platform scope).
 *   - Every role has >= 1 permission.
 *   - No role references a perm outside the vocabulary.
 *   - No self or project perms in any role.
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

final class RolePermissions
{
    /** Every role in the platform. Same order as the contract's roles[]. */
    public const ROLES = [
        Role::Owner,
        Role::Admin,
        Role::Editor,
        Role::Viewer,
    ];

    /**
     * @var array<string, list<Permission>> role → perm map.
     *
     * Only contains platform and platform/project perms;
     * self perms are universal (granted by the resolver's Step 1)
     * and project perms are for tenant users via TenantRole.
     */
    private const ROLE_PERMISSIONS = [
        'OWNER' => [
            Permission::AthensProjectDelete,
            Permission::AthensProjectUpdate,
            Permission::AthensProjectView,
            Permission::AthensServicesDisable,
            Permission::AthensServicesEnable,
            Permission::AthensTeamInvite,
            Permission::AthensTeamRemove,
            Permission::HeliosInvitationsCreate,
            Permission::HeliosInvitationsRevoke,
            Permission::HeliosMembersInvite,
            Permission::HeliosMembersRemove,
            Permission::HeliosMembersView,
            Permission::HeliosRolesAssign,
            Permission::HeliosRolesRevoke,
            Permission::HeliosTenantTransfer,
            Permission::MercuryApi_keysManage,
            Permission::MercuryUsersRead,
            Permission::MercuryUsersWrite,
            Permission::MuseAuthorCreate,
            Permission::MuseAuthorDelete,
            Permission::MuseAuthorRead,
            Permission::MuseBlogCreate,
            Permission::MuseBlogRead,
        ],
        'ADMIN' => [
            Permission::AthensProjectUpdate,
            Permission::AthensProjectView,
            Permission::AthensServicesDisable,
            Permission::AthensServicesEnable,
            Permission::AthensTeamInvite,
            Permission::AthensTeamRemove,
            Permission::HeliosInvitationsCreate,
            Permission::HeliosInvitationsRevoke,
            Permission::HeliosMembersInvite,
            Permission::HeliosMembersRemove,
            Permission::HeliosMembersView,
            Permission::HeliosRolesAssign,
            Permission::HeliosRolesRevoke,
            Permission::MercuryApi_keysManage,
            Permission::MercuryUsersRead,
            Permission::MercuryUsersWrite,
            Permission::MuseAuthorCreate,
            Permission::MuseAuthorRead,
            Permission::MuseBlogCreate,
            Permission::MuseBlogRead,
        ],
        'EDITOR' => [
            Permission::AthensProjectView,
            Permission::MercuryUsersRead,
            Permission::MuseAuthorCreate,
            Permission::MuseAuthorRead,
            Permission::MuseBlogCreate,
            Permission::MuseBlogRead,
        ],
        'VIEWER' => [
            Permission::AthensProjectView,
            Permission::MercuryUsersRead,
            Permission::MuseAuthorRead,
            Permission::MuseBlogRead,
        ],
    ];

    /**
     * @var array<string, PermScope> perm → scope lookup. Populated at module
     * load. The two-track resolver in Helios checks PERM_SCOPE[perm] to
     * decide which path (platform-user vs tenant-user) is valid.
     */
    public const PERM_SCOPE = [
        'mercury:user:read:self' => PermScope::Self,
        'mercury:user:write:self' => PermScope::Self,
        'helios:tenant:switch:self' => PermScope::Self,
        'athens:project:view' => PermScope::Platform,
        'athens:project:update' => PermScope::Platform,
        'athens:project:delete' => PermScope::Platform,
        'athens:services:enable' => PermScope::Platform,
        'athens:services:disable' => PermScope::Platform,
        'athens:team:invite' => PermScope::Platform,
        'athens:team:remove' => PermScope::Platform,
        'mercury:users:read' => PermScope::Platform,
        'mercury:users:write' => PermScope::Platform,
        'mercury:api_keys:manage' => PermScope::Platform,
        'muse:blog:create' => PermScope::Platform,
        'muse:blog:read' => PermScope::Platform,
        'muse:author:create' => PermScope::Platform,
        'muse:author:delete' => PermScope::Platform,
        'helios:tenant:transfer' => PermScope::Platform,
        'helios:members:view' => PermScope::Platform,
        'helios:members:invite' => PermScope::Platform,
        'helios:members:remove' => PermScope::Platform,
        'helios:roles:assign' => PermScope::Platform,
        'helios:roles:revoke' => PermScope::Platform,
        'helios:invitations:create' => PermScope::Platform,
        'helios:invitations:revoke' => PermScope::Platform,
        'muse:posts:read' => PermScope::Project,
        'muse:posts:write' => PermScope::Project,
        'muse:posts:delete' => PermScope::Project,
        'muse:drafts:read' => PermScope::Project,
        'muse:drafts:write' => PermScope::Project,
        'muse:author:read' => PermScope::PlatformProject,
    ];

    /**
     * Return the permission array for a role. Empty for unknown roles.
     *
     * @return list<Permission>
     */
    public static function resolve(Role $role): array
    {
        return self::ROLE_PERMISSIONS[$role->value] ?? [];
    }

    /**
     * True if role is granted perm. Both args must be typed enums — a typo
     * in a perm string will not satisfy the Permission type.
     */
    public static function has(Role $role, Permission $perm): bool
    {
        foreach (self::resolve($role) as $p) {
            if ($p === $perm) {
                return true;
            }
        }
        return false;
    }

    /**
     * True if p is a known Permission value. Used for runtime validation of
     * strings arriving from an untrusted source (request bodies, DB rows, etc).
     */
    public static function isValidPermission(Permission $perm): bool
    {
        return in_array($perm, Permission::cases(), true);
    }

    /**
     * Return the scope of a perm, or null if the perm is tenant-defined
     * (not in the contract vocabulary).
     */
    public static function scopeOf(Permission $perm): ?PermScope
    {
        return self::PERM_SCOPE[$perm->value] ?? null;
    }

    /**
     * True if perm has scope 'self' (universal — granted without any role
     * lookup). Used by the resolver's Step 1.
     */
    public static function isSelfScope(Permission $perm): bool
    {
        return self::scopeOf($perm) === PermScope::Self;
    }

    /**
     * True if perm is grantable via the platform-user path (scope is
     * 'platform' or 'platform/project').
     */
    public static function isPlatformGrantable(Permission $perm): bool
    {
        $s = self::scopeOf($perm);
        return $s === PermScope::Platform || $s === PermScope::PlatformProject;
    }

    /**
     * True if perm is grantable via the tenant-user path. Scope 'project'
     * and 'platform/project' are grantable. Any perm NOT in PERM_SCOPE is
     * treated as tenant-defined and therefore grantable via TenantRole.
     */
    public static function isTenantGrantable(string $perm): bool
    {
        if (!isset(self::PERM_SCOPE[$perm])) {
            return true;
        }
        $s = self::PERM_SCOPE[$perm];
        return $s === PermScope::Project || $s === PermScope::PlatformProject;
    }
}
